# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 68452112cd1507ee4f4ea3461d9a01db4043fe13

{
  "title": "Продам всякую всячину",
  "description": "Все очень б/у"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/17/
Content-Type: application/json
Authorization: Token ec0e1f8814e478ca5d1053d2fad9aa8834ebffea

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json
Authorization: Token ec0e1f8814e478ca5d1053d2fad9aa8834ebffea

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2022-05-01
Content-Type: application/json

###
DELETE {{baseUrl}}/advertisements/18/
Content-Type: application/json
Authorization: Token ec0e1f8814e478ca5d1053d2fad9aa8834ebffea
 